#!/bin/bash
# Claude Mind Manager — Stop Hook (Auto-Save + Learnings + Session Summary)
# Saves active context on EVERY response (overwrite, no growth).
# Extracts learnings every N messages, session summaries every 2N messages.
# Counter is per session_id (not per project) to handle Desktop chat switching.
# Cost: zero API calls — pure file operations (~50ms).

INPUT=$(cat)
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // empty')
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // empty')
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')

if [ -z "$PROJECT_DIR" ] || [ -z "$TRANSCRIPT_PATH" ]; then
  exit 0
fi

# --- Configurable ---
LEARNINGS_INTERVAL="${MIND_LEARNINGS_INTERVAL:-10}"
CONTEXT_MAX_BYTES="${MIND_CONTEXT_MAX_BYTES:-8000}"
CONTEXT_TAIL_LINES="${MIND_CONTEXT_TAIL_LINES:-150}"

# --- Message counter (per-session, in /tmp) ---
# Use session_id if available, fall back to project hash
if [ -n "$SESSION_ID" ]; then
  COUNTER_KEY="$SESSION_ID"
else
  COUNTER_KEY=$(echo "$PROJECT_DIR" | tr '/\\: ' '----' | sed 's/^-*//')
fi
COUNTER_FILE="/tmp/mind-msg-count-${COUNTER_KEY}"

# Read counter (incremented by session-tracker.sh on UserPromptSubmit)
COUNT=0
if [ -f "$COUNTER_FILE" ]; then
  COUNT=$(cat "$COUNTER_FILE" 2>/dev/null || echo "0")
fi

# --- Extract context from transcript (ALWAYS) ---
RAW_CONTEXT=""
if [ -f "$TRANSCRIPT_PATH" ]; then
  RAW_CONTEXT=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r '
      select(.type == "assistant" or .role == "assistant") |
      if .message then
        (.message.content // empty) | if type == "array" then
          map(select(.type == "text") | .text) | join("\n")
        elif type == "string" then .
        else empty end
      elif .content then
        if (.content | type) == "array" then
          .content | map(select(.type == "text") | .text) | join("\n")
        elif (.content | type) == "string" then .content
        else empty end
      else empty end
    ' 2>/dev/null | \
    tail -c "$CONTEXT_MAX_BYTES" 2>/dev/null)
fi

if [ -z "$RAW_CONTEXT" ]; then
  exit 0
fi

# --- Collect recent learnings for inclusion in active-context ---
LEARNINGS_SRC="$PROJECT_DIR/.claude-mind/learnings"
RECENT_LEARNINGS=""
if [ -d "$LEARNINGS_SRC" ]; then
  RECENT_LEARNINGS=$(ls -t "$LEARNINGS_SRC"/session-*.md 2>/dev/null | head -3 | \
    xargs -I{} grep -h '^\- ' {} 2>/dev/null | tail -5)
fi

# --- Write active-context.md (EVERY response — overwrites, no growth) ---
RULES_DIR="$PROJECT_DIR/.claude/rules"
mkdir -p "$RULES_DIR"
CONTEXT_FILE="$RULES_DIR/active-context.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

cat > "$CONTEXT_FILE" <<CTXEOF
---
# Active Context — auto-generated by Claude Mind Manager
# Last updated: ${TIMESTAMP}
# Trigger: auto-save (message ${COUNT})
# This file is a rule WITHOUT globs: — it loads at EVERY session start in this project.
# DO NOT EDIT MANUALLY — overwritten after every Claude response.
---

# Session Context (auto-saved)

The following is a summary of the current working session, automatically extracted
during conversation. Use this to maintain continuity.

## Current Session Extract

${RAW_CONTEXT}

## Recent Learnings

The following corrections and decisions were extracted from recent sessions.
Apply these to avoid repeating past mistakes.

${RECENT_LEARNINGS:-No learnings recorded yet.}
CTXEOF

# === Below: periodic tasks (only every N messages) ===

if [ "$COUNT" -lt 1 ]; then
  exit 0
fi

MIND_DIR="$PROJECT_DIR/.claude-mind"

# --- Session summary (every 2x learnings interval) ---
SUMMARY_INTERVAL=$((LEARNINGS_INTERVAL * 2))
if [ $((COUNT % SUMMARY_INTERVAL)) -eq 0 ]; then
  SESSIONS_DIR="$MIND_DIR/sessions"
  mkdir -p "$SESSIONS_DIR"
  SESSION_TS=$(date '+%Y-%m-%d-%H%M')
  SESSION_FILE="$SESSIONS_DIR/session-${SESSION_TS}.md"

  S_DECISIONS=$(echo "$RAW_CONTEXT" | grep -iE '(decided|chose|using|switched to|went with|selected)' 2>/dev/null | head -5)
  S_ERRORS=$(echo "$RAW_CONTEXT" | grep -iE '(error|failed|exception|fix|bug)' 2>/dev/null | head -5)
  S_FILE_CHANGES=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r 'select(.type == "tool_use") | select(.name == "Write" or .name == "Edit") |
      "\(.name): \(.input.file_path // "unknown" | tostring | .[0:80])"' 2>/dev/null | sort -u | head -10)
  S_COMMANDS=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r 'select(.type == "tool_use") | select(.name == "Bash") |
      .input.command // empty | .[0:80]' 2>/dev/null | head -8)

  cat > "$SESSION_FILE" <<SESSEOF
# Session Summary — ${SESSION_TS}

- **Messages:** ${COUNT}
- **Project:** ${PROJECT_DIR}

## Decisions
${S_DECISIONS:-_No explicit decisions detected._}

## Errors Encountered
${S_ERRORS:-_No errors detected._}

## File Changes
${S_FILE_CHANGES:-_No file changes detected._}

## Key Commands
${S_COMMANDS:-_No commands detected._}
SESSEOF

  # Detect new dependencies
  NEW_DEPS=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r 'select(.type == "tool_use") | select(.name == "Bash") |
      .input.command // empty' 2>/dev/null | \
    grep -oE '(npm install|pip install|cargo add) [^ ]+' 2>/dev/null | sort -u)
  if [ -n "$NEW_DEPS" ]; then
    mkdir -p "$MIND_DIR"
    echo "" >> "$MIND_DIR/suggestions.md"
    echo "## Session ${SESSION_TS}" >> "$MIND_DIR/suggestions.md"
    echo "- New dependencies: ${NEW_DEPS}" >> "$MIND_DIR/suggestions.md"
  fi
fi

# --- Extract learnings (every N messages) ---
if [ $((COUNT % LEARNINGS_INTERVAL)) -eq 0 ]; then
  LEARNINGS_DIR="$MIND_DIR/learnings"
  mkdir -p "$LEARNINGS_DIR"

  TODAY=$(date '+%Y-%m-%d')
  LEARNINGS_FILE="$LEARNINGS_DIR/session-${TODAY}.md"

  LEARNINGS=""
  if [ -f "$TRANSCRIPT_PATH" ]; then
    LEARNINGS=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
      jq -r '
        select(.type == "assistant" or .role == "assistant") |
        if .message then
          (.message.content // empty) | if type == "array" then
            map(select(.type == "text") | .text) | join("\n")
          elif type == "string" then .
          else empty end
        elif .content then
          if (.content | type) == "array" then
            .content | map(select(.type == "text") | .text) | join("\n")
          elif (.content | type) == "string" then .content
          else empty end
        else empty end
      ' 2>/dev/null | \
      grep -iE '(instead of|should have|fix(ed)?:|error:|mistake|correction|NEVER |MUST |ALWAYS |decided to|chose |switched from|changed .* to |the issue was|root cause|workaround)' 2>/dev/null | \
      head -30 | \
      sed 's/^[[:space:]]*/- /' 2>/dev/null)
  fi

  if [ -n "$LEARNINGS" ]; then
    if [ ! -f "$LEARNINGS_FILE" ]; then
      cat > "$LEARNINGS_FILE" <<LEOF
# Session Learnings — ${TODAY}
# Auto-extracted by Claude Mind Manager (Stop hook)
# Format: Korrektur-Flywheel — corrections and decisions from conversation

LEOF
    fi

    cat >> "$LEARNINGS_FILE" <<LEOF
## Extract at $(date '+%H:%M:%S') (message ${COUNT})

${LEARNINGS}

LEOF
  fi
fi

exit 0
