#!/bin/bash
# Claude Mind Manager — Stop Hook (Auto-Save + Learnings)
# Periodically saves active context during conversation (every N messages).
# Writes to .claude/rules/active-context.md (auto-loaded in project scope).
# Also extracts learnings (corrections, errors, decisions) to .claude-mind/learnings/.
# Cost: zero API calls — pure file operations.

INPUT=$(cat)
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // empty')
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // empty')

if [ -z "$PROJECT_DIR" ] || [ -z "$TRANSCRIPT_PATH" ]; then
  exit 0
fi

# --- Configurable ---
SAVE_INTERVAL="${MIND_AUTO_SAVE_INTERVAL:-10}"
CONTEXT_MAX_BYTES="${MIND_CONTEXT_MAX_BYTES:-8000}"
CONTEXT_TAIL_LINES="${MIND_CONTEXT_TAIL_LINES:-150}"

# --- Message counter (per-project, in /tmp) ---
HASH=$(echo "$PROJECT_DIR" | tr '/\\: ' '----' | sed 's/^-*//')
COUNTER_FILE="/tmp/mind-msg-count-${HASH}"

# Increment counter
if [ -f "$COUNTER_FILE" ]; then
  COUNT=$(cat "$COUNTER_FILE" 2>/dev/null || echo "0")
else
  COUNT=0
fi
COUNT=$((COUNT + 1))
echo "$COUNT" > "$COUNTER_FILE"

# Only save every N messages
if [ $((COUNT % SAVE_INTERVAL)) -ne 0 ]; then
  exit 0
fi

# --- Extract context from transcript ---
RAW_CONTEXT=""
if [ -f "$TRANSCRIPT_PATH" ]; then
  RAW_CONTEXT=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r '
      select(.type == "assistant" or .role == "assistant") |
      if .message then
        (.message.content // empty) | if type == "array" then
          map(select(.type == "text") | .text) | join("\n")
        elif type == "string" then .
        else empty end
      elif .content then
        if (.content | type) == "array" then
          .content | map(select(.type == "text") | .text) | join("\n")
        elif (.content | type) == "string" then .content
        else empty end
      else empty end
    ' 2>/dev/null | \
    tail -c "$CONTEXT_MAX_BYTES" 2>/dev/null)
fi

if [ -z "$RAW_CONTEXT" ]; then
  exit 0
fi

# --- Collect recent learnings for inclusion in active-context ---
LEARNINGS_SRC="$PROJECT_DIR/.claude-mind/learnings"
RECENT_LEARNINGS=""
if [ -d "$LEARNINGS_SRC" ]; then
  # Get last 5 learning entries from most recent files (tail of newest files)
  RECENT_LEARNINGS=$(ls -t "$LEARNINGS_SRC"/session-*.md 2>/dev/null | head -3 | \
    xargs -I{} grep -h '^\- ' {} 2>/dev/null | tail -5)
fi

# --- Write active-context.md ---
RULES_DIR="$PROJECT_DIR/.claude/rules"
mkdir -p "$RULES_DIR"
CONTEXT_FILE="$RULES_DIR/active-context.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

cat > "$CONTEXT_FILE" <<CTXEOF
---
# Active Context — auto-generated by Claude Mind Manager
# Last updated: ${TIMESTAMP}
# Trigger: auto-save (message ${COUNT})
# This file is a rule WITHOUT globs: — it loads at EVERY session start in this project.
# DO NOT EDIT MANUALLY — overwritten periodically during conversation.
---

# Session Context (auto-saved)

The following is a summary of the current working session, automatically extracted
during conversation. Use this to maintain continuity.

## Current Session Extract

${RAW_CONTEXT}

## Recent Learnings

The following corrections and decisions were extracted from recent sessions.
Apply these to avoid repeating past mistakes.

${RECENT_LEARNINGS:-No learnings recorded yet.}
CTXEOF

# --- Extract learnings (corrections, errors, decisions) ---
MIND_DIR="$PROJECT_DIR/.claude-mind"
LEARNINGS_DIR="$MIND_DIR/learnings"
mkdir -p "$LEARNINGS_DIR"

TODAY=$(date '+%Y-%m-%d')
LEARNINGS_FILE="$LEARNINGS_DIR/session-${TODAY}.md"

# Extract patterns that indicate learnings from transcript
# Look for: corrections ("not X, use Y"), errors ("failed because"), decisions ("decided to", "chose")
LEARNINGS=""
if [ -f "$TRANSCRIPT_PATH" ]; then
  LEARNINGS=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r '
      select(.type == "assistant" or .role == "assistant") |
      if .message then
        (.message.content // empty) | if type == "array" then
          map(select(.type == "text") | .text) | join("\n")
        elif type == "string" then .
        else empty end
      elif .content then
        if (.content | type) == "array" then
          .content | map(select(.type == "text") | .text) | join("\n")
        elif (.content | type) == "string" then .content
        else empty end
      else empty end
    ' 2>/dev/null | \
    grep -iE '(instead of|should have|fix(ed)?:|error:|mistake|correction|NEVER |MUST |ALWAYS |decided to|chose |switched from|changed .* to |the issue was|root cause|workaround)' 2>/dev/null | \
    head -30 | \
    sed 's/^[[:space:]]*/- /' 2>/dev/null)
fi

# Only write if learnings were found
if [ -n "$LEARNINGS" ]; then
  # Append to today's learnings file (don't overwrite — accumulate per day)
  if [ ! -f "$LEARNINGS_FILE" ]; then
    cat > "$LEARNINGS_FILE" <<LEOF
# Session Learnings — ${TODAY}
# Auto-extracted by Claude Mind Manager (Stop hook)
# Format: Korrektur-Flywheel — corrections and decisions from conversation

LEOF
  fi

  cat >> "$LEARNINGS_FILE" <<LEOF
## Extract at $(date '+%H:%M:%S') (message ${COUNT})

${LEARNINGS}

LEOF
fi

exit 0
