#!/bin/bash
# Claude Mind Manager — Save Active Context
# Extracts last session context from transcript JSONL and writes it to
# .claude/rules/active-context.md (rule without globs: = always loaded).
# Called by pre-compact.sh before context compaction.
# Cost: zero API calls — pure file operations.

INPUT=$(cat)
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // empty')
TRIGGER=$(echo "$INPUT" | jq -r '.trigger // "unknown"')
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // empty')

if [ -z "$PROJECT_DIR" ] || [ -z "$TRANSCRIPT_PATH" ]; then
  exit 0
fi

# --- Configurable ---
CONTEXT_MAX_BYTES="${MIND_CONTEXT_MAX_BYTES:-3000}"
CONTEXT_TAIL_LINES="${MIND_CONTEXT_TAIL_LINES:-50}"

# --- Ensure .claude/rules/ exists ---
RULES_DIR="$PROJECT_DIR/.claude/rules"
mkdir -p "$RULES_DIR"

CONTEXT_FILE="$RULES_DIR/active-context.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# --- Extract last assistant messages from transcript ---
RAW_CONTEXT=""
if [ -f "$TRANSCRIPT_PATH" ]; then
  # JSONL: each line is a JSON object. Extract assistant messages.
  # Use tail to get recent entries, jq to filter assistant role,
  # then tail -c to limit size. Defensive: ignore jq errors.
  RAW_CONTEXT=$(tail -"$CONTEXT_TAIL_LINES" "$TRANSCRIPT_PATH" 2>/dev/null | \
    jq -r '
      select(.type == "assistant" or .role == "assistant") |
      if .message then
        (.message.content // empty) | if type == "array" then
          map(select(.type == "text") | .text) | join("\n")
        elif type == "string" then .
        else empty end
      elif .content then
        if (.content | type) == "array" then
          .content | map(select(.type == "text") | .text) | join("\n")
        elif (.content | type) == "string" then .content
        else empty end
      else empty end
    ' 2>/dev/null | \
    tail -c "$CONTEXT_MAX_BYTES" 2>/dev/null)
fi

# --- Only write if we got content ---
if [ -z "$RAW_CONTEXT" ]; then
  exit 0
fi

# --- Write active-context.md as rule without globs (always loaded) ---
cat > "$CONTEXT_FILE" <<CTXEOF
---
# Active Context — auto-generated by Claude Mind Manager
# Last updated: ${TIMESTAMP}
# Trigger: ${TRIGGER}
# This file is a rule WITHOUT globs: — it loads at EVERY session start.
# DO NOT EDIT MANUALLY — overwritten on each compaction.
# Add to .gitignore if you don't want to share session context with team.
---

# Session Context (auto-saved)

The following is a summary of the last working session, automatically extracted
before context compaction. Use this to continue where the previous session left off.

## Last Session Extract

${RAW_CONTEXT}
CTXEOF

echo "[Mind Manager] Active context saved to .claude/rules/active-context.md ($(echo "$RAW_CONTEXT" | wc -l | tr -d ' ') lines)"

exit 0
